# PANDAS Module

### IRIS Data Set

In [28]:
import numpy as np

In [1]:
import pandas as pd

In [5]:
from sklearn import datasets

In [6]:
ir = datasets.load_iris()
iris = pd.DataFrame(iris.data)

In [7]:
iris.head()

0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2

In [16]:
from sklearn.linear_model import LinearRegression
clf  = LinearRegression()

In [14]:
#to split the data for trainig ans testing
from sklearn import cross_validation

#it will return 4 things Xtraining , Ytraining , XTest , YTest
X_Train , X_Test , Y_Train , Y_Test = cross_validation.train_test_split(iris,ir.target,test_size = 0.2)


In [17]:
clf.fit(X_Train,Y_Train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [18]:
Y_pred = clf.predict(X_Test).astype(int)
Y_pred

array([1, 1, 1, 1, 2, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 2, 1, 0])

In [27]:
Y_Test

array([1, 1, 1, 2, 2, 2, 2, 0, 2, 1, 0, 1, 1, 1, 2, 2, 2, 1, 1, 1, 0, 1, 0,
       1, 2, 1, 2, 2, 2, 0])

# Classification Report

In [24]:
from sklearn.metrics import confusion_matrix as cm
cm(Y_Test,Y_pred)

array([[ 5,  0,  0],
       [ 1, 12,  0],
       [ 0, 10,  2]])

In [25]:
from sklearn.metrics import classification_report as cr

In [26]:
cr(Y_Test,Y_pred)

'             precision    recall  f1-score   support\n\n          0       0.83      1.00      0.91         5\n          1       0.55      0.92      0.69        13\n          2       1.00      0.17      0.29        12\n\navg / total       0.78      0.63      0.56        30\n'