# PANDAS Module

### IRIS Data Set

In [31]:
import numpy as np

In [32]:
import pandas as pd

In [33]:
from sklearn import datasets

In [41]:
ir = datasets.load_iris()
print(ir.target)
iris = pd.DataFrame(ir.data)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [35]:
print(iris.columns)
iris.head()

RangeIndex(start=0, stop=4, step=1)


0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2

In [36]:
from sklearn.linear_model import LinearRegression
clf  = LinearRegression()

In [37]:
#to split the data for trainig ans testing
from sklearn import cross_validation

#it will return 4 things Xtraining , Ytraining , XTest , YTest
X_Train , X_Test , Y_Train , Y_Test = cross_validation.train_test_split(iris,ir.target,test_size = 0.2)


In [38]:
clf.fit(X_Train,Y_Train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [39]:
Y_pred = clf.predict(X_Test)
Y_pred

array([  1.02057607e+00,   1.58812198e+00,   1.09741657e+00,
         1.19576631e+00,   2.99210316e-02,   2.19241049e+00,
         8.78801964e-01,   1.31170512e+00,  -5.78408707e-04,
         4.76415372e-02,   1.75107263e+00,   1.78359695e+00,
         1.78168171e+00,   1.55258934e+00,  -2.48656383e-02,
         1.38855288e+00,  -5.64872332e-02,   9.08541032e-01,
         2.14030059e-01,  -1.69200335e-01,   1.18195684e+00,
        -4.12429654e-02,   3.64986603e-02,   2.04408057e+00,
         1.20512555e+00,  -1.48113080e-03,  -2.37818282e-01,
         1.26034541e+00,   1.68535684e+00,   1.83336133e+00])

In [40]:
Y_Test

array([1, 2, 1, 1, 0, 2, 1, 1, 0, 0, 2, 2, 2, 2, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       2, 1, 0, 0, 1, 2, 2])

# Classification Report

In [26]:
from sklearn.metrics import confusion_matrix as cm
cm(Y_Test,Y_pred)

array([[12,  0,  0],
       [ 3,  5,  0],
       [ 0,  8,  2]])

In [27]:
from sklearn.metrics import classification_report as cr

In [29]:
print(cr(Y_Test,Y_pred))

             precision    recall  f1-score   support

          0       0.80      1.00      0.89        12
          1       0.38      0.62      0.48         8
          2       1.00      0.20      0.33        10

avg / total       0.76      0.63      0.59        30

