In [2]:
from PIL import Image
import numpy as np

In [25]:
fname="D:/DOCUMENTS/portal.png"
img=np.asarray(Image.open(fname), dtype=np.float32)
img

array([[ 18.,  17.,  18., ...,  17.,  16.,  17.],
       [ 18.,  20.,  17., ...,  19.,  20.,  20.],
       [ 19.,  19.,  17., ...,  22.,  22.,  21.],
       ..., 
       [ 32.,  32.,  32., ...,  17.,  18.,  19.],
       [ 36.,  31.,  45., ...,  17.,  18.,  17.],
       [ 32.,  37.,  60., ...,  16.,  19.,  17.]], dtype=float32)

In [20]:
def common_size(a1, a2):
    """Chop-off the first rows and cols from the two numpy arrays a1
    and a2 so that they end up having the same size.
    >>> print common_size(np.array([[0, 0],
    ...                             [1, 2],
    ...                             [3, 4]]),
    ...                   np.array([[0, 5, 6],
    ...                             [0, 7, 8]]))
    (array([[1, 2],
           [3, 4]]), array([[5, 6],
           [7, 8]]))
    """
    (r1, c1) = a1.shape
    (r2, c2) = a2.shape
    return (a1[r1-r2 if r1>r2 else 0:,
               c1-c2 if c1>c2 else 0:],
            a2[r2-r1 if r2>r1 else 0::,
               c2-c1 if c2>c1 else 0:])

In [26]:
def np_from_img(fname):
    return np.asarray(Image.open(fname), dtype=np.float32)

def save_as_img(ar, fname):
    Image.fromarray(ar.round().astype(np.uint8)).save(fname)

def norm(ar):
    return 255*np.absolute(ar)/np.max(ar)

In [27]:
from scipy import signal as sg

In [39]:
def gradient(im):
    imv, imh = common_size(sg.convolve(im, [[1., -1.]]),
                           sg.convolve(im, [[1.], [-1.]]))
    return (np.power(imv, 1)+np.power(imh, 1))/2

In [44]:
print(sg.convolve(img, [[1.],[-1.]]))
norm(sg.convolve(img, [[1.],[-1.]]))

[[  1.80000000e+01   1.70000000e+01   1.80000000e+01 ...,   1.70000000e+01
    1.60000000e+01   1.70000000e+01]
 [  5.57907636e-14   3.00000000e+00  -1.00000000e+00 ...,   2.00000000e+00
    4.00000000e+00   3.00000000e+00]
 [  1.00000000e+00  -1.00000000e+00   2.18952426e-14 ...,   3.00000000e+00
    2.00000000e+00   1.00000000e+00]
 ..., 
 [  4.00000000e+00  -1.00000000e+00   1.30000000e+01 ...,   5.81066093e-14
    9.37390085e-14  -2.00000000e+00]
 [ -4.00000000e+00   6.00000000e+00   1.50000000e+01 ...,  -1.00000000e+00
    1.00000000e+00  -7.57912274e-14]
 [ -3.20000000e+01  -3.70000000e+01  -6.00000000e+01 ...,  -1.60000000e+01
   -1.90000000e+01  -1.70000000e+01]]


array([[  2.27227726e+01,   2.14603958e+01,   2.27227726e+01, ...,
          2.14603958e+01,   2.01980190e+01,   2.14603958e+01],
       [  7.04289329e-14,   3.78712869e+00,   1.26237619e+00, ...,
          2.52475238e+00,   5.04950476e+00,   3.78712869e+00],
       [  1.26237619e+00,   1.26237619e+00,   2.76400335e-14, ...,
          3.78712869e+00,   2.52475238e+00,   1.26237619e+00],
       ..., 
       [  5.04950476e+00,   1.26237619e+00,   1.64108906e+01, ...,
          7.33524027e-14,   1.18333891e-13,   2.52475238e+00],
       [  5.04950476e+00,   7.57425737e+00,   1.89356441e+01, ...,
          1.26237619e+00,   1.26237619e+00,   9.56770402e-14],
       [  4.03960381e+01,   4.67079201e+01,   7.57425766e+01, ...,
          2.01980190e+01,   2.39851494e+01,   2.14603958e+01]], dtype=float32)

In [3]:
"save_as_img(norm(sg.convolve(img, [[1.],\
                                   [-1.]])),\
            'D:/DOCUMENTS/portal-h.png')\
save_as_img(norm(sg.convolve(img, [[1., -1.]])),\
            'D:/DOCUMENTS/portal-v.png')\
save_as_img((sg.convolve(img, [[1.],[-1.]])),\
            'D:/DOCUMENTS/portal wonorm -h.png')\
save_as_img((gradient(img)),\
            'D:/DOCUMENTS/portal wgrad  -h.png')"


"save_as_img(norm(sg.convolve(img, [[1.],                                   [-1.]])),            'D:/DOCUMENTS/portal-h.png')save_as_img(norm(sg.convolve(img, [[1., -1.]])),            'D:/DOCUMENTS/portal-v.png')save_as_img((sg.convolve(img, [[1.],[-1.]])),            'D:/DOCUMENTS/portal wonorm -h.png')save_as_img((gradient(img)),            'D:/DOCUMENTS/portal wgrad  -h.png')"

In [3]:
help("modules")


Please wait a moment while I gather a list of all available modules...



C:\Users\simra\Anaconda3\lib\site-packages\IPython\kernel\__init__.py:13: ShimWarning: The `IPython.kernel` package has been deprecated since IPython 4.0.You should import from ipykernel or jupyter_client instead.
  "You should import from ipykernel or jupyter_client instead.", ShimWarning)
C:\Users\simra\Anaconda3\lib\site-packages\odo\backends\pandas.py:94: FutureWarning: pandas.tslib is deprecated and will be removed in a future version.
You can access NaTType as type(pandas.NaT)
  @convert.register((pd.Timestamp, pd.Timedelta), (pd.tslib.NaTType, type(None)))
C:\Users\simra\Anaconda3\lib\site-packages\blaze\server\server.py:17: ExtDeprecationWarning: Importing flask.ext.cors is deprecated, use flask_cors instead.
  from flask.ext.cors import cross_origin
C:\Users\simra\Anaconda3\lib\site-packages\bokeh\util\deprecation.py:34: BokehDeprecationWarning: MPL compatibility can no longer be successfully maintained, and is now deprecated. All MPL compat functions will be removed completel

Crypto              chunk               msgpack             spyder_pylint
Cython              click               msilib              sqlalchemy
IPython             cloudpickle         msvcrt              sqlite3
OleFileIO_PL        clyent              multipledispatch    sre_compile
OpenSSL             cmath               multiprocessing     sre_constants
PIL                 cmd                 navigator_updater   sre_parse
PyQt5               code                nbconvert           ssl
__future__          codecs              nbformat            sspi
_ast                codeop              netbios             sspicon
_asyncio            collections         netrc               stat
_bisect             colorama            networkx            statistics
_blake2             colorsys            nltk                statsmodels
_bootlocale         commctrl            nntplib             storemagic
_bz2                compileall          nose                string
_cffi_backend       comtypes