In [3]:
import numpy as np
import matplotlib.pyplot as plt

freq = 100 
def sine(x, phase=0, freq=freq):
    return np.sin((freq * x + phase))

dist = np.linspace(-0.5,0.5,256)
x,y = np.meshgrid(dist, dist)
grid = (x**2+y**2)

testpattern = sine(grid, freq=freq)
methods = [None, 'none', 'nearest', 'bilinear', 'bicubic', 'spline16',
           'spline36', 'hanning', 'hamming', 'hermite', 'kaiser', 'quadric',
           'catrom', 'gaussian', 'bessel', 'mitchell', 'sinc', 'lanczos']

fig, axes = plt.subplots(3, 6, figsize=(96, 48))
fig.subplots_adjust(hspace=0.3, wspace=0.05)

for ax, interp_method in zip(axes.flat, methods):
    ax.imshow(testpattern , interpolation=interp_method, cmap='gray')
    ax.set_title(interp_method)

x,y



(array([[-0.5       , -0.49607843, -0.49215686, ...,  0.49215686,
          0.49607843,  0.5       ],
        [-0.5       , -0.49607843, -0.49215686, ...,  0.49215686,
          0.49607843,  0.5       ],
        [-0.5       , -0.49607843, -0.49215686, ...,  0.49215686,
          0.49607843,  0.5       ],
        ..., 
        [-0.5       , -0.49607843, -0.49215686, ...,  0.49215686,
          0.49607843,  0.5       ],
        [-0.5       , -0.49607843, -0.49215686, ...,  0.49215686,
          0.49607843,  0.5       ],
        [-0.5       , -0.49607843, -0.49215686, ...,  0.49215686,
          0.49607843,  0.5       ]]),
 array([[-0.5       , -0.5       , -0.5       , ..., -0.5       ,
         -0.5       , -0.5       ],
        [-0.49607843, -0.49607843, -0.49607843, ..., -0.49607843,
         -0.49607843, -0.49607843],
        [-0.49215686, -0.49215686, -0.49215686, ..., -0.49215686,
         -0.49215686, -0.49215686],
        ..., 
        [ 0.49215686,  0.49215686,  0.49215686, ...,

In [2]:
path="D:\DOCUMENTS\ML A-Z - Hands On Python and R In Data Science\02 -------------------------- Part 1 Data Preprocessing --------------------------\attached_files\012 Categorical Data\Categorical-Data.zip\Categorical_Data\Data.csv"

In [3]:
path=path.replace("\\","/")

In [4]:
print(path)

D:/DOCUMENTS/ML A-Z - Hands On Python and R In Data Science -------------------------- Part 1 Data Preprocessing --------------------------ttached_files
 Categorical Data/Categorical-Data.zip/Categorical_Data/Data.csv


In [2]:
path1="D:/DOCUMENTS/Data.csv"

In [3]:
df1=pd.read_csv(path1)
df1

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [4]:
from sklearn.preprocessing import Imputer

In [5]:
array=np.array([1,2,3])
array[:]

array([1, 2, 3])

In [6]:
X=df1.iloc[:,:-1]
Y=df1.iloc[:,3]
type(X),type(Y)
X=X.values
Y=Y.values
X,Y,df1

(array([['France', 44.0, 72000.0],
        ['Spain', 27.0, 48000.0],
        ['Germany', 30.0, 54000.0],
        ['Spain', 38.0, 61000.0],
        ['Germany', 40.0, nan],
        ['France', 35.0, 58000.0],
        ['Spain', nan, 52000.0],
        ['France', 48.0, 79000.0],
        ['Germany', 50.0, 83000.0],
        ['France', 37.0, 67000.0]], dtype=object),
 array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'], dtype=object),
    Country   Age   Salary Purchased
 0   France  44.0  72000.0        No
 1    Spain  27.0  48000.0       Yes
 2  Germany  30.0  54000.0        No
 3    Spain  38.0  61000.0        No
 4  Germany  40.0      NaN       Yes
 5   France  35.0  58000.0       Yes
 6    Spain   NaN  52000.0        No
 7   France  48.0  79000.0       Yes
 8  Germany  50.0  83000.0        No
 9   France  37.0  67000.0       Yes)

In [8]:
imputer1 = Imputer(missing_values='NaN',strategy='mean',axis=0)
X[:,1:]=imputer1.fit_transform(X[:,1:])

In [10]:
X[:,1:]

array([[44.0, 72000.0],
       [27.0, 48000.0],
       [30.0, 54000.0],
       [38.0, 61000.0],
       [40.0, 63777.77777777778],
       [35.0, 58000.0],
       [38.77777777777778, 52000.0],
       [48.0, 79000.0],
       [50.0, 83000.0],
       [37.0, 67000.0]], dtype=object)

In [9]:
np.array(X[:,1:],dtype=int)

array([[   44, 72000],
       [   27, 48000],
       [   30, 54000],
       [   38, 61000],
       [   40, 63777],
       [   35, 58000],
       [   38, 52000],
       [   48, 79000],
       [   50, 83000],
       [   37, 67000]])

NameError: name 'NotebookApp' is not defined

In [28]:
np.dtype([('f1', np.int16)])
help(np)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.


In [26]:
import numpy as np
x = np.arange(-5, 5, 1)
y = np.arange(-5, 5, 1)
xx, yy = np.meshgrid(x, y, sparse=False,indexing='xy')
z = np.sin(xx**2 + yy**2) / (xx**2 + yy**2)
plt.show(),xx,yy

C:\Users\simra\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: invalid value encountered in true_divide
  """


(None, array([[-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
        [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
        [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
        [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
        [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
        [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
        [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
        [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
        [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
        [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4]]), array([[-5, -5, -5, -5, -5, -5, -5, -5, -5, -5],
        [-4, -4, -4, -4, -4, -4, -4, -4, -4, -4],
        [-3, -3, -3, -3, -3, -3, -3, -3, -3, -3],
        [-2, -2, -2, -2, -2, -2, -2, -2, -2, -2],
        [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
        [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
        [ 3,  3,  3,  3,  3,  3,  3,  3,  3,  3],
        [ 4,  4,  4,  4,  4,  4,  4,  4,  4

In [11]:
sum=0
for i in range(np.size(xx)):
    sum=xx[0,i]*yy[i,0]+sum
print(sum)    

85
