In [1]:
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn import decomposition
from sklearn import cross_validation

C:\Users\simra\Anaconda3\lib\site-packages\sklearn\cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [12]:
diab = datasets.load_breast_cancer()
data = diab.data

scaler = StandardScaler()
data_scaled = scaler.fit_transform(data)
data_scaled

array([[ 1.09706398, -2.07333501,  1.26993369, ...,  2.29607613,
         2.75062224,  1.93701461],
       [ 1.82982061, -0.35363241,  1.68595471, ...,  1.0870843 ,
        -0.24388967,  0.28118999],
       [ 1.57988811,  0.45618695,  1.56650313, ...,  1.95500035,
         1.152255  ,  0.20139121],
       ..., 
       [ 0.70228425,  2.0455738 ,  0.67267578, ...,  0.41406869,
        -1.10454895, -0.31840916],
       [ 1.83834103,  2.33645719,  1.98252415, ...,  2.28998549,
         1.91908301,  2.21963528],
       [-1.80840125,  1.22179204, -1.81438851, ..., -1.74506282,
        -0.04813821, -0.75120669]])

In [11]:
pca = decomposition.PCA()
pca.fit(data_scaled)
variance = pca.explained_variance_
variance

array([  1.32816077e+01,   5.69135461e+00,   2.81794898e+00,
         1.98064047e+00,   1.64873055e+00,   1.20735661e+00,
         6.75220114e-01,   4.76617140e-01,   4.16894812e-01,
         3.50693457e-01,   2.93915696e-01,   2.61161370e-01,
         2.41357496e-01,   1.57009724e-01,   9.41349650e-02,
         7.98628010e-02,   5.93990378e-02,   5.26187835e-02,
         4.94775918e-02,   3.11594025e-02,   2.99728939e-02,
         2.74394025e-02,   2.43408378e-02,   1.80550070e-02,
         1.54812714e-02,   8.17763986e-03,   6.90046388e-03,
         1.58933787e-03,   7.48803097e-04,   1.33044823e-04])

In [4]:
tot_sum = variance.sum()
sum1 = 0
count = 0
for i in range(len(variance)):
    sum1= sum1 + variance[len(variance)-i-1]
    temp = sum1 / tot_sum
    count = count + 1
    if temp > 0.05:
        break
        
count       

21

In [5]:
pca.n_components = len(variance) - count
data_pca = pca.fit_transform(data_scaled)

In [6]:
data_pca.shape

(569, 9)

In [7]:
import time
from sklearn.svm import SVC

In [8]:
#Before PCA


start = time.time()
svc = SVC()
x_train , x_test , y_train , y_test = cross_validation.train_test_split(data_scaled , diab.target , test_size = 0.2)
svc.fit(x_train,y_train)
print(svc.score(x_test , y_test))
end = time.time()
print(end-start)

0.982456140351
0.08649086952209473


In [9]:
#After PCA

start = time.time()
svc = SVC()
x_train , x_test , y_train , y_test = cross_validation.train_test_split(data_pca , diab.target , test_size = 0.2)
svc.fit(x_train,y_train)
print(svc.score(x_test , y_test))
end = time.time()
print(end-start)

0.947368421053
0.0070209503173828125


In [10]:
x = [1,2,3]
x1 = scaler.fit_transform(x)
x1

C:\Users\simra\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:586: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
C:\Users\simra\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:649: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)


array([-1.22474487,  0.        ,  1.22474487])