In [7]:
import numpy as np
from matplotlib import style
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
style.use('ggplot')

In [11]:
x=np.random.random_integers(50, size=(20,2))
x

C:\Users\simra\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 50 + 1) instead
  """Entry point for launching an IPython kernel.


array([[ 2, 37],
       [18, 47],
       [22, 12],
       [ 3, 14],
       [50,  1],
       [15, 22],
       [19,  9],
       [47, 14],
       [38, 16],
       [41, 34],
       [30, 42],
       [14, 37],
       [14, 31],
       [ 2, 21],
       [22, 16],
       [ 1, 41],
       [12, 43],
       [48, 30],
       [ 1, 40],
       [50, 30]])

In [13]:
kmeans = KMeans(n_clusters=2, random_state=0)
kmeans.fit(x)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=2, n_init=10, n_jobs=1, precompute_distances='auto',
    random_state=0, tol=0.0001, verbose=0)

In [15]:
kmeans.cluster_centers_

array([[ 10.18181818,  34.09090909],
       [ 37.44444444,  18.        ]])

In [16]:
kmeans.labels_

array([0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1])